# Generated by Django 5.2.3 on 2025-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='discord_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
