# Generated by Django 5.2.3 on 2025-11-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('encrypted_image', models.ImageField(upload_to='drops/encrypted_drops/')),
                ('price_sol', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_supply', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.walletuser')),
            ],
        ),
    ]
