# Generated by Django 5.2.3 on 2025-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='encryption_key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drop',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='orignal_drops/'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='creator',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='drop',
            name='encrypted_image',
            field=models.ImageField(upload_to='encrypted_drops/'),
        ),
    ]
