# Generated by Django 5.2.3 on 2025-11-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_drop_encryption_key_drop_original_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='current_supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drop',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_wallet', models.CharField(max_length=44)),
                ('transaction_signature', models.CharField(max_length=200)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drops.drop')),
            ],
            options={
                'unique_together': {('drop', 'buyer_wallet')},
            },
        ),
    ]
