# Generated by Django 5.2.3 on 2025-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_drop_current_supply_drop_is_sold_out_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='original_drops/'),
        ),
    ]
